"""Public surface of the semantic layer.

Most users only need ``Catalog``, ``Cube``, the field types
(``Measure`` / ``Dimension`` / ``TimeDimension``), and
``SemanticQuery``. The rest is exported for callers building their own
tooling on top of the compiler (custom validators, MCP servers,
prompt rendering, etc.).
"""

from __future__ import annotations

from semql.catalog import Catalog
from semql.compile import MAX_UNGROUPED_ROWS, ColumnMeta, Compiled, compile_query
from semql.docs import render_catalog_markdown
from semql.errors import (
    CompileError,
    CrossBackendError,
    FederationError,
    FilterTypeError,
    JoinPathError,
    PhaseDeferredError,
    PlaceholderError,
    ResolveError,
    SemQLError,
    UnknownIdentifierError,
)
from semql.federate import FederatedPlan, MergePlan, compile_federated_query
from semql.introspect import (
    CATALOG_CUBES,
    CATALOG_DIMENSIONS,
    CATALOG_MEASURES,
    META_CUBES,
    ResolvedQuery,
    iter_cubes,
    iter_fields,
    iter_joins,
    resolve_field,
    resolve_query,
)
from semql.lookups import materialize as materialize_lookup
from semql.lookups import resolve as resolve_lookup
from semql.model import (
    AggLiteral,
    AuthContext,
    Backend,
    BaseField,
    ChartTypeLiteral,
    Cube,
    CubeSource,
    DerivedTable,
    Dimension,
    DimTypeLiteral,
    FormatLiteral,
    GranularityLiteral,
    Join,
    Lookup,
    LookupLoader,
    LookupValues,
    Measure,
    ResolutionContext,
    ScopePredicate,
    Segment,
    TableRef,
    TimeDimension,
    View,
)
from semql.plan import (
    DrilldownSuggestion,
    DrilldownSuggestions,
    Presentation,
    QueryIntent,
    QueryPlan,
    QueryStep,
    RouterDecision,
    RouterPath,
)
from semql.prompt import (
    build_drilldown_prompt_fragment,
    build_planner_prompt_fragment,
    build_presenter_prompt_fragment,
    build_query_generator_prompt_fragment,
    build_router_prompt_fragment,
    render_catalogue_block,
)
from semql.safe import is_safe_select
from semql.spec import (
    BoolExpr,
    CompareWindow,
    Filter,
    FilterOp,
    SemanticQuery,
    TimeWindow,
)
from semql.units import (
    DEFAULT_REGISTRY,
    IncompatibleUnits,
    Registry,
    UnitError,
    UnknownUnit,
)
from semql.validate import ValidationError, validate
from semql.visualize import VizColumn, VizDecision, decide_visualization

__all__ = [
    "AggLiteral",
    "AuthContext",
    "Backend",
    "BaseField",
    "BoolExpr",
    "CATALOG_CUBES",
    "CATALOG_DIMENSIONS",
    "CATALOG_MEASURES",
    "Catalog",
    "ChartTypeLiteral",
    "ColumnMeta",
    "CompareWindow",
    "CompileError",
    "Compiled",
    "CrossBackendError",
    "Cube",
    "CubeSource",
    "DerivedTable",
    "DimTypeLiteral",
    "DEFAULT_REGISTRY",
    "Dimension",
    "DrilldownSuggestion",
    "DrilldownSuggestions",
    "FederatedPlan",
    "FederationError",
    "Filter",
    "FilterOp",
    "FilterTypeError",
    "FormatLiteral",
    "IncompatibleUnits",
    "GranularityLiteral",
    "Join",
    "JoinPathError",
    "Lookup",
    "LookupLoader",
    "LookupValues",
    "MAX_UNGROUPED_ROWS",
    "MergePlan",
    "META_CUBES",
    "Measure",
    "PhaseDeferredError",
    "PlaceholderError",
    "Presentation",
    "QueryIntent",
    "QueryPlan",
    "QueryStep",
    "Registry",
    "ResolutionContext",
    "ResolveError",
    "ResolvedQuery",
    "RouterDecision",
    "RouterPath",
    "ScopePredicate",
    "Segment",
    "SemQLError",
    "SemanticQuery",
    "TableRef",
    "TimeDimension",
    "TimeWindow",
    "UnitError",
    "UnknownIdentifierError",
    "UnknownUnit",
    "ValidationError",
    "View",
    "VizColumn",
    "VizDecision",
    "build_drilldown_prompt_fragment",
    "build_planner_prompt_fragment",
    "build_presenter_prompt_fragment",
    "build_query_generator_prompt_fragment",
    "build_router_prompt_fragment",
    "compile_federated_query",
    "compile_query",
    "decide_visualization",
    "is_safe_select",
    "iter_cubes",
    "iter_fields",
    "iter_joins",
    "materialize_lookup",
    "render_catalog_markdown",
    "render_catalogue_block",
    "resolve_field",
    "resolve_lookup",
    "resolve_query",
    "validate",
]
