"""Public surface of the semantic layer.

Most users only need ``Catalog``, ``Cube``, the field types
(``Measure`` / ``Dimension`` / ``TimeDimension``), and
``SemanticQuery``. The rest is exported for callers building their own
tooling on top of the compiler (custom validators, MCP servers,
prompt rendering, etc.).
"""

from __future__ import annotations

from semql.catalog import Catalog
from semql.compile import MAX_UNGROUPED_ROWS, ColumnMeta, CompiledQuery, compile_query
from semql.cost import BudgetExceededError, CostEstimate, QueryBudget, estimate_cost
from semql.diff import CatalogDiff, Change, ChangeKind, diff_catalogs
from semql.docs import render_catalog_markdown
from semql.errors import (
    AuthError,
    CompileError,
    CrossDialectError,
    FederationError,
    FilterTypeError,
    JoinPathError,
    PhaseDeferredError,
    PlaceholderError,
    ResolveError,
    SemQLError,
    UnknownIdentifierError,
)
from semql.federate import (
    BridgeJoin,
    DimensionOutput,
    FederatedPlan,
    FragmentColumn,
    MeasureOutput,
    MergePlan,
    MergeSpec,
    compile_federated_query,
)
from semql.hooks import CubePromptHook, ErrorTransformHook
from semql.introspect import (
    CATALOG_CUBES,
    CATALOG_DIMENSIONS,
    CATALOG_MEASURES,
    META_CUBES,
    ResolvedQuery,
    iter_cubes,
    iter_fields,
    iter_joins,
    resolve_field,
    resolve_query,
    validate_and_resolve,
)
from semql.lint import LintFinding, LintReport, lint_catalog
from semql.logical import (
    Aggregate,
    ColumnRef,
    CompareSplit,
    OrderBy,
    Predicate,
    Project,
    Scan,
    TimeBreakdown,
    apply_rollup_to_plan,
    partition_scans,
    to_logical_plan,
)

# Note: ``LogicalPlan`` is intentionally NOT re-exported at the top
# level. The IR is load-bearing for the compiler but isn't yet
# serialisable (no model_dump / model_validate / schema_version).
# Callers that need the IR — for debugging, snapshot tests, or
# federation routing — import via the explicit module path
# (``from semql.logical import LogicalPlan``). The naming review
# 2026-06 calls for removing it from ``__all__`` until the wire
# format is stable; this is the corresponding narrowing of the
# top-level surface.
from semql.lookups import enrich_result
from semql.lookups import materialize as materialize_lookup
from semql.lookups import resolve as resolve_lookup
from semql.model import (
    AggLiteral,
    AuthContext,
    BaseField,
    ChartTypeLiteral,
    Cube,
    CubeSource,
    DerivedTable,
    Dialect,
    Dimension,
    DimTypeLiteral,
    Entity,
    FormatLiteral,
    GlossaryEntry,
    GranularityLiteral,
    Join,
    Lookup,
    LookupEnricher,
    LookupLoader,
    LookupValues,
    Measure,
    NamedCTE,
    PartitionedScan,
    PhysicalTable,
    Provenance,
    ResolutionContext,
    Rollup,
    ScopePredicate,
    Segment,
    StabilityLiteral,
    TimeDimension,
    TimePartition,
    TimePartitionedSource,
    View,
)
from semql.parse import ParseError, ParserDecision, parse_sql_statement
from semql.plan import (
    DrilldownSuggestion,
    DrilldownSuggestions,
    Presentation,
    QueryIntent,
    QueryPlan,
    QueryStep,
    RouterDecision,
    RouteTo,
)
from semql.retrieve import (
    EmbeddingProvider,
    HybridRetriever,
    MMRWrapper,
    NumpyCosineRetriever,
    Retriever,
    SQLiteBM25Retriever,
    build_default_retriever,
)
from semql.rewrite import (
    AddFilter,
    ChangeGranularity,
    ChangeTimeWindow,
    Drilldown,
    RemoveFilter,
    RewriteOp,
    rewrite,
)
from semql.safe import is_read_only_statement
from semql.spec import (
    BoolExpr,
    CompareWindow,
    Filter,
    FilterOp,
    InlineDerived,
    InlineDerivedOp,
    SavedQuery,
    SemanticQuery,
    SemanticQueryDefaults,
    TimeWindow,
)
from semql.units import (
    DEFAULT_REGISTRY,
    IncompatibleUnits,
    Registry,
    UnitError,
    UnknownUnit,
)
from semql.validate import ValidationError, ValidationWarning, validate
from semql.visualize import VizColumn, VizDecision, decide_visualization

__all__ = [
    "AggLiteral",
    "AuthContext",
    "AuthError",
    "Dialect",
    "BudgetExceededError",
    "CostEstimate",
    "BaseField",
    "BoolExpr",
    "BridgeJoin",
    "CatalogDiff",
    "Change",
    "ChangeKind",
    "Aggregate",
    "ColumnRef",
    "CompareSplit",
    "OrderBy",
    "Predicate",
    "Project",
    "Scan",
    "TimeBreakdown",
    "CATALOG_CUBES",
    "CATALOG_DIMENSIONS",
    "CATALOG_MEASURES",
    "Catalog",
    "ChartTypeLiteral",
    "CubePromptHook",
    "ColumnMeta",
    "CompareWindow",
    "CompileError",
    "CompiledQuery",
    "CrossDialectError",
    "Cube",
    "CubeSource",
    "DerivedTable",
    "DimTypeLiteral",
    "DEFAULT_REGISTRY",
    "Dimension",
    "Entity",
    "DimensionOutput",
    "DrilldownSuggestion",
    "DrilldownSuggestions",
    "EmbeddingProvider",
    "ErrorTransformHook",
    "FederatedPlan",
    "FederationError",
    "Filter",
    "FilterOp",
    "FilterTypeError",
    "FormatLiteral",
    "FragmentColumn",
    "GlossaryEntry",
    "HybridRetriever",
    "IncompatibleUnits",
    "InlineDerived",
    "InlineDerivedOp",
    "GranularityLiteral",
    "Join",
    "JoinPathError",
    "Lookup",
    "LookupEnricher",
    "LookupLoader",
    "LookupValues",
    "MAX_UNGROUPED_ROWS",
    "ParserDecision",
    "ParseError",
    "parse_sql_statement",
    "MMRWrapper",
    "MergePlan",
    "MergeSpec",
    "META_CUBES",
    "AddFilter",
    "ChangeGranularity",
    "ChangeTimeWindow",
    "Drilldown",
    "Measure",
    "MeasureOutput",
    "NamedCTE",
    "NumpyCosineRetriever",
    "RemoveFilter",
    "RewriteOp",
    "PhaseDeferredError",
    "PlaceholderError",
    "Presentation",
    "QueryIntent",
    "QueryPlan",
    "QueryStep",
    "Registry",
    "ResolutionContext",
    "SavedQuery",
    "ResolveError",
    "ResolvedQuery",
    "Retriever",
    "Rollup",
    "RouterDecision",
    "RouteTo",
    "SQLiteBM25Retriever",
    "ScopePredicate",
    "Segment",
    "SemQLError",
    "StabilityLiteral",
    "SemanticQuery",
    "SemanticQueryDefaults",
    "PhysicalTable",
    "Provenance",
    "TimeDimension",
    "PartitionedScan",
    "TimePartition",
    "TimePartitionedSource",
    "TimeWindow",
    "UnitError",
    "UnknownIdentifierError",
    "UnknownUnit",
    "ValidationError",
    "ValidationWarning",
    "View",
    "VizColumn",
    "VizDecision",
    "build_default_retriever",
    "compile_federated_query",
    "compile_query",
    "decide_visualization",
    "diff_catalogs",
    "estimate_cost",
    "is_read_only_statement",
    "QueryBudget",
    "iter_cubes",
    "iter_fields",
    "iter_joins",
    "enrich_result",
    "materialize_lookup",
    "lint_catalog",
    "LintFinding",
    "LintReport",
    "render_catalog_markdown",
    "resolve_field",
    "resolve_lookup",
    "rewrite",
    "resolve_query",
    "validate_and_resolve",
    "validate",
    "apply_rollup_to_plan",
    "partition_scans",
    "to_logical_plan",
]
