#!/usr/bin/env -S uv run
"""Emit per-package API reference markdown from griffe.

Griffe walks the packages' source under ``packages/<pkg>/src`` and we
project the public surface (everything in ``__all__`` of the top-level
module) into one markdown file per package under ``docs/api/``.

Run from the repo root:

    uv run scripts/gen_api_docs.py

Idempotent — overwrites ``docs/api/*.md`` on each invocation. Skip
running this from CI for now; the layer-1 ribbon mentioned it explicitly.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterable
from pathlib import Path

import griffe

# (importable module name, packages/<dir> name) — kept explicit so the
# script doesn't have to guess at hyphen-vs-underscore conventions.
PACKAGES: tuple[tuple[str, str], ...] = (
    ("semql", "semql"),
    ("semql_mcp", "semql-mcp"),
    ("semql_erd", "semql-erd"),
)

REPO_ROOT = Path(__file__).resolve().parent.parent


def _search_paths() -> list[str]:
    """Each package's ``src/`` directory — griffe looks here to find the
    importable module by name."""
    return [str(REPO_ROOT / "packages" / pkg_dir / "src") for _, pkg_dir in PACKAGES]


def _signature(obj: griffe.Object) -> str:
    """Render a function/method signature with parameter defaults.

    Griffe stores parameters as ``Parameter`` objects with ``name``,
    ``annotation``, ``default``, and ``kind``. We render the same shape
    the source declares, ignoring annotation rendering edge cases —
    the goal is a *reference*, not a verbatim type signature."""
    if not isinstance(obj, griffe.Function):
        return ""
    params: list[str] = []
    for p in obj.parameters:
        piece = p.name
        if p.annotation is not None:
            piece += f": {p.annotation}"
        if p.default is not None:
            piece += f" = {p.default}"
        params.append(piece)
    return f"({', '.join(params)})"


def _docstring(obj: griffe.Object) -> str:
    """Return the raw docstring body, or an empty string."""
    if obj.docstring is None:
        return ""
    return obj.docstring.value.strip()


def _render_member(obj: griffe.Object) -> list[str]:
    """One markdown section per public member: heading, signature, doc."""
    name = obj.name
    kind = obj.kind.value if obj.kind else "object"
    lines: list[str] = [f"### `{name}` ({kind})", ""]

    sig = _signature(obj)
    if sig:
        lines.append(f"```python\n{name}{sig}\n```")
        lines.append("")

    doc = _docstring(obj)
    if doc:
        lines.append(doc)
        lines.append("")

    return lines


def _public_members(module: griffe.Module) -> Iterable[griffe.Object]:
    """Yield members named in ``__all__`` (in declaration order)."""
    exports = module.exports
    if not exports:
        return ()
    # ``exports`` is the parsed __all__ list — strings or Name nodes.
    names: list[str] = []
    for entry in exports:
        if isinstance(entry, str):
            names.append(entry)
        else:
            names.append(getattr(entry, "name", str(entry)))
    seen: set[str] = set()
    for name in names:
        if name in seen or name not in module.members:
            continue
        seen.add(name)
        yield module.members[name]  # type: ignore[misc]


def render_package(package: str) -> str:
    """Render one markdown document for ``package`` (top-level module)."""
    module = griffe.load(package, search_paths=_search_paths())
    if not isinstance(module, griffe.Module):
        raise TypeError(f"griffe.load({package!r}) returned non-module {type(module).__name__}.")

    lines: list[str] = [
        f"# `{package}` — API reference",
        "",
        "Generated by `scripts/gen_api_docs.py`. Do not edit by hand.",
        "",
    ]
    if module.docstring is not None:
        lines.append(module.docstring.value.strip())
        lines.append("")

    for member in _public_members(module):
        lines.extend(_render_member(member))

    return "\n".join(lines).rstrip() + "\n"


def write_docs(
    out_dir: Path,
    packages: Iterable[tuple[str, str]] = PACKAGES,
) -> list[Path]:
    """Render each package and write to ``<out_dir>/<module>.md``."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for module_name, _ in packages:
        target = out_dir / f"{module_name}.md"
        target.write_text(render_package(module_name))
        written.append(target)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "docs" / "api",
        help="Output directory (default: docs/api/).",
    )
    args = parser.parse_args(argv)
    written = write_docs(args.out)
    for path in written:
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
