"""Tests for the auto-generated per-cube ``query_<cube>`` MCP tools.

Each exposed cube gets a tool whose signature is constrained to the
cube's actual measures/dimensions/time-dimensions. The point is
discoverability: a planner LLM that lists tools sees ``query_orders``
with ``measures: Literal["revenue", "count"]`` instead of having to
intuit valid identifiers and prefix them with the cube name itself.

Multi-cube queries still go through ``query_semantic``. Hidden cubes
(``expose_in_prompt=False``) and META reflection cubes are excluded
from the auto-generated tools.
"""

from __future__ import annotations

import asyncio
from collections.abc import Awaitable
from typing import Any

from fastmcp import Client
from semql import (
    Catalog,
    Cube,
    Dialect,
    Dimension,
    Measure,
    TimeDimension,
)
from semql_mcp import MCPServer


def _run[T](coro: Awaitable[T]) -> T:
    return asyncio.run(coro)  # type: ignore[arg-type]


def _cat() -> Catalog:
    orders = Cube(
        name="orders",
        backend=Dialect.POSTGRES,
        table="orders",
        alias="o",
        description="One row per order; revenue/count grouped by region.",
        measures=[
            Measure(name="revenue", sql="{o}.amount", agg="sum", unit="currency"),
            Measure(name="count", sql="*", agg="count", unit="count"),
        ],
        dimensions=[
            Dimension(name="region", sql="{o}.region", type="string"),
            Dimension(name="status", sql="{o}.status", type="string"),
        ],
        time_dimensions=[TimeDimension(name="created_at", sql="{o}.created_at")],
    )
    hidden = Cube(
        name="internal_only",
        backend=Dialect.POSTGRES,
        table="internal",
        alias="i",
        expose_in_prompt=False,
        dimensions=[Dimension(name="x", sql="{i}.x", type="string")],
    )
    return Catalog([orders, hidden])


def _server(**kwargs: Any) -> MCPServer:  # noqa: ANN401
    return MCPServer(_cat(), **kwargs)


def _client(server: MCPServer) -> Client[Any]:
    return Client(server.mcp)


# ---------------------------------------------------------------------------
# Registration: one tool per exposed cube; hidden / META cubes excluded.
# ---------------------------------------------------------------------------


def test_tool_registered_for_each_exposed_cube() -> None:
    s = _server()

    async def fetch() -> set[str]:
        async with _client(s) as c:
            tools = await c.list_tools()
            return {t.name for t in tools}

    names = _run(fetch())
    assert "query_orders" in names


def test_hidden_cube_does_not_get_auto_tool() -> None:
    s = _server()

    async def fetch() -> set[str]:
        async with _client(s) as c:
            tools = await c.list_tools()
            return {t.name for t in tools}

    names = _run(fetch())
    assert "query_internal_only" not in names


def test_meta_cubes_do_not_get_auto_tools() -> None:
    """The META reflection cubes (catalog_cubes / catalog_measures /
    catalog_dimensions) are inserted into every Catalog. They shouldn't
    each generate a query_* tool — the planner queries them through
    query_semantic when it wants introspection."""
    s = _server()

    async def fetch() -> set[str]:
        async with _client(s) as c:
            tools = await c.list_tools()
            return {t.name for t in tools}

    names = _run(fetch())
    for meta in ("catalog_cubes", "catalog_measures", "catalog_dimensions"):
        assert f"query_{meta}" not in names


# ---------------------------------------------------------------------------
# Tool description / metadata
# ---------------------------------------------------------------------------


def test_tool_description_includes_cube_description() -> None:
    s = _server()

    async def fetch() -> str:
        async with _client(s) as c:
            tools = await c.list_tools()
            tool = next(t for t in tools if t.name == "query_orders")
            return tool.description or ""

    desc = _run(fetch())
    assert "One row per order" in desc


def test_tool_input_schema_enumerates_cube_measures() -> None:
    """The JSON Schema generated by FastMCP should constrain the
    ``measures`` parameter to the cube's actual measure names —
    so a planner that consults the schema gets autocomplete-style
    guidance."""
    s = _server()

    async def fetch() -> dict[str, Any]:
        async with _client(s) as c:
            tools = await c.list_tools()
            tool = next(t for t in tools if t.name == "query_orders")
            return tool.inputSchema or {}

    schema = _run(fetch())
    # Drill into the measures property's enum.
    props = schema.get("properties", {})
    measures_schema = props.get("measures", {})
    # The Literal[...] becomes either an enum in the items schema or
    # a oneOf — accept either by walking the dict.
    text = str(measures_schema)
    assert "revenue" in text
    assert "count" in text


def test_tool_input_schema_enumerates_cube_dimensions() -> None:
    s = _server()

    async def fetch() -> dict[str, Any]:
        async with _client(s) as c:
            tools = await c.list_tools()
            tool = next(t for t in tools if t.name == "query_orders")
            return tool.inputSchema or {}

    schema = _run(fetch())
    text = str(schema.get("properties", {}).get("dimensions", {}))
    assert "region" in text
    assert "status" in text


# ---------------------------------------------------------------------------
# Call behaviour: per-cube tool == query_semantic with prefixed names.
# ---------------------------------------------------------------------------


def test_query_cube_compiles_with_prefixed_names() -> None:
    s = _server()

    async def call() -> dict[str, Any]:
        async with _client(s) as c:
            result = await c.call_tool(
                "query_orders",
                {"measures": ["revenue"], "dimensions": ["region"]},
            )
            return result.data  # type: ignore[no-any-return]

    out = _run(call())
    assert "SUM" in out["sql"].upper()
    assert out["columns"] == ["region", "revenue"]
    assert out["backend"] == "postgres"


def test_query_cube_threads_time_window() -> None:
    s = _server()

    async def call() -> dict[str, Any]:
        async with _client(s) as c:
            result = await c.call_tool(
                "query_orders",
                {
                    "measures": ["count"],
                    "time_window": {
                        "dimension": "created_at",
                        "granularity": "day",
                        "range": ["2026-01-01", "2026-02-01"],
                    },
                },
            )
            return result.data  # type: ignore[no-any-return]

    out = _run(call())
    assert "created_at_day" in out["columns"]


def test_query_cube_threads_filters_with_bare_dim_name() -> None:
    """Filters use bare dimension names (no cube prefix) — the tool
    auto-prefixes when building the SemanticQuery."""
    s = _server()

    async def call() -> dict[str, Any]:
        async with _client(s) as c:
            result = await c.call_tool(
                "query_orders",
                {
                    "measures": ["count"],
                    "dimensions": ["region"],
                    "filters": [{"dimension": "status", "op": "eq", "values": ["paid"]}],
                },
            )
            return result.data  # type: ignore[no-any-return]

    out = _run(call())
    assert "paid" in out["params"].values()


def test_query_cube_threads_limit_and_order() -> None:
    s = _server()

    async def call() -> dict[str, Any]:
        async with _client(s) as c:
            result = await c.call_tool(
                "query_orders",
                {
                    "measures": ["revenue"],
                    "dimensions": ["region"],
                    "limit": 5,
                    "order": [["revenue", "desc"]],
                },
            )
            return result.data  # type: ignore[no-any-return]

    out = _run(call())
    assert "LIMIT 5" in out["sql"]
    assert "ORDER BY" in out["sql"].upper()


# ---------------------------------------------------------------------------
# Exec mode also covers the per-cube tools.
# ---------------------------------------------------------------------------


def test_query_cube_executes_when_executor_set() -> None:
    """The per-cube tool routes through the same compile + execute
    path as ``query_execute``, so the executor sees rows."""
    calls: list[tuple[str, dict[str, Any]]] = []

    def fake_exec(sql: str, params: dict[str, Any]) -> list[dict[str, Any]]:
        calls.append((sql, params))
        return [{"region": "us", "revenue": 100}]

    s = MCPServer(_cat(), executor=fake_exec)

    async def call() -> dict[str, Any]:
        async with _client(s) as c:
            result = await c.call_tool(
                "query_orders",
                {"measures": ["revenue"], "dimensions": ["region"]},
            )
            return result.data  # type: ignore[no-any-return]

    out = _run(call())
    assert len(calls) == 1
    assert out["rows"] == [{"region": "us", "revenue": 100}]


# ---------------------------------------------------------------------------
# Validation: unknown measure / dimension names rejected.
# ---------------------------------------------------------------------------


def test_query_cube_unknown_measure_rejected() -> None:
    """FastMCP / Pydantic enforce the Literal enum, so an unknown
    measure name fails at the tool boundary — the FastMCP client
    raises ``ToolError`` rather than letting the bogus argument
    through. Either ``ToolError`` or a structured error payload is
    an acceptable surface; both prevent the bad name from reaching
    the compiler."""
    from fastmcp.exceptions import ToolError

    s = _server()

    async def call() -> Any:  # noqa: ANN401
        async with _client(s) as c:
            return await c.call_tool(
                "query_orders",
                {"measures": ["no_such_measure"]},
            )

    raised: Exception | None = None
    try:
        result = _run(call())
    except ToolError as exc:  # noqa: BLE001
        raised = exc
        result = None
    if raised is not None:
        assert "no_such_measure" in str(raised) or "literal" in str(raised).lower()
    else:
        assert result is not None
        data: Any = result.data
        assert result.is_error or (isinstance(data, dict) and "error" in data)


# ---------------------------------------------------------------------------
# Pure-dim cubes (no measures): tool still works, allows ungrouped row
# listings via the dimensions parameter.
# ---------------------------------------------------------------------------


def test_query_cube_with_only_dimensions_compiles() -> None:
    """A cube referenced in dim-only mode should still produce a
    SELECT DISTINCT body (the existing semql contract)."""
    s = _server()

    async def call() -> dict[str, Any]:
        async with _client(s) as c:
            result = await c.call_tool(
                "query_orders",
                {"dimensions": ["region"]},
            )
            return result.data  # type: ignore[no-any-return]

    out = _run(call())
    assert "DISTINCT" in out["sql"].upper()
