"""Render a :class:`IntrospectionResult` as Python source code.

The output is a self-contained module that ``import``s from
``semql.model`` and defines a ``CUBES: list[Cube]`` constant. The dev
review loop is: run the introspector, open the file, search for
``# TODO: review`` comments, edit by hand. Heuristic annotations
get rendered inline so the dev sees *why* the tool picked each guess.
"""

from __future__ import annotations

import textwrap

from semql.model import Cube, Join

from semql_introspect._introspect import IntrospectionResult


def emit_python(result: IntrospectionResult, *, header: str | None = None) -> str:
    """Render the introspection result as a single Python module.

    ``header`` overrides the default docstring at the top — useful for
    CLI invocations that want to record the connection string / schema
    in the file so the diff carries provenance."""
    annotations_by_field: dict[tuple[str, str], list[str]] = {}
    for ann in result.annotations:
        annotations_by_field.setdefault((ann.cube, ann.field), []).append(ann.reason)

    lines: list[str] = []
    lines.append(_header(header))
    lines.append("from __future__ import annotations\n")
    lines.append("")
    lines.append("from semql.model import (")
    lines.append("    Dialect,")
    lines.append("    Cube,")
    lines.append("    Dimension,")
    lines.append("    Join,")
    lines.append("    Measure,")
    lines.append("    TimeDimension,")
    lines.append(")")
    lines.append("")
    lines.append("")

    for cube in result.cubes:
        lines.append(_render_cube(cube, annotations_by_field))
        lines.append("")

    lines.append("CUBES: list[Cube] = [")
    for cube in result.cubes:
        lines.append(f"    {_cube_var(cube.name)},")
    lines.append("]")

    return "\n".join(lines) + "\n"


def _header(custom: str | None) -> str:
    if custom is not None:
        return f'"""{custom}"""\n\n'
    return (
        '"""Auto-generated by semql-introspect.\n\n'
        "Review every ``# TODO: review`` comment before promoting this\n"
        "file to a production catalog. The heuristic-inferred measures\n"
        "and dimensions are educated guesses, not authoritative — the\n"
        "introspector errs on the side of surfacing structure so a human\n"
        "review pass can prune.\n"
        '"""\n\n'
    )


def _cube_var(cube_name: str) -> str:
    """Variable name for a cube in the emitted module."""
    return f"{cube_name}_cube"


def _render_cube(
    cube: Cube,
    annotations: dict[tuple[str, str], list[str]],
) -> str:
    var = _cube_var(cube.name)
    lines: list[str] = []
    lines.append(f"{var} = Cube(")
    lines.append(f"    name={cube.name!r},")
    lines.append(f"    backend=Dialect.{cube.backend.name},")
    lines.append(f"    table={cube.table!r},")
    lines.append(f"    alias={cube.alias!r},")
    if cube.primary_key is not None:
        lines.append(f"    primary_key={cube.primary_key!r},")

    if cube.measures:
        lines.append("    measures=[")
        for m in cube.measures:
            todo = annotations.get((cube.name, m.name))
            if todo:
                lines.append(_indent_comment(todo, 8))
            lines.append(f"        Measure(name={m.name!r}, sql={m.sql!r}, agg={m.agg!r}),")
        lines.append("    ],")
    if cube.dimensions:
        lines.append("    dimensions=[")
        for d in cube.dimensions:
            todo = annotations.get((cube.name, d.name))
            if todo:
                lines.append(_indent_comment(todo, 8))
            inner = f"name={d.name!r}, sql={d.sql!r}, type={d.type!r}"
            if d.foreign_key is not None:
                inner += f", foreign_key={d.foreign_key!r}"
            lines.append(f"        Dimension({inner}),")
        lines.append("    ],")
    if cube.time_dimensions:
        lines.append("    time_dimensions=[")
        for td in cube.time_dimensions:
            lines.append(f"        TimeDimension(name={td.name!r}, sql={td.sql!r}),")
        lines.append("    ],")
    if cube.joins:
        lines.append("    joins=[")
        for j in cube.joins:
            lines.append(_render_join(j))
        lines.append("    ],")

    # S7 — emit placeholder grounding fields with TODO comments so the
    # introspect → review flow is explicit. The user fills these in
    # (or runs `semql suggest` to draft them via LLM).
    lines.append("    # TODO: review — questions users might literally ask of this cube.")
    lines.append("    questions=[],")
    lines.append("    # TODO: review — keywords for lexical retrieval (acronyms preserved).")
    lines.append("    keywords=[],")

    lines.append(")")
    return "\n".join(lines)


def _render_join(j: Join) -> str:
    return f"        Join(to={j.to!r}, relationship={j.relationship!r}, on={j.on!r}),"


def _indent_comment(reasons: list[str], indent: int) -> str:
    prefix = " " * indent + "# TODO: review — "
    wrapper = textwrap.TextWrapper(
        initial_indent=prefix,
        subsequent_indent=" " * indent + "#   ",
        width=88,
    )
    lines: list[str] = []
    for reason in reasons:
        lines.append(wrapper.fill(reason))
    return "\n".join(lines)


__all__ = ["emit_python"]
